### ISSUE TITLE
Asserting Two Types Not Throwing Error

### ISSUE THREAD

**Issue by oxters168** [garronej/tsafe#27]
Hi there, I've been looking for a way to compare two types at runtime and have stumbled upon your repository.

I have a function that takes a generic type argument and returns a value of that type. This value is retrieved from a firebase server. Firebase does not properly store arrays, so what I'm attempting to do is compare the generic type argument received at runtime and check if it is an array. If so then convert the object received from firebase to an array.

The issue I have run into is that I can't seem to get the `assert` in combination with `Equals` to throw a runtime error. For example, if I simply put `assert<Equals<{}, []>>`, nothing happens. Is this the intended behavior, am I missing something?

**Comment by garronej** [comment]
Hello @oxters168,  

`tsafe` is for type level testing. tsafe's `assert<Equals<A,B>>()` is only for getting a TypeScript error if `A` and `B` aren't the same type.  
It's usefull when you have a complex function that infer the return type from it's input, to test that you've defined your return type correctly.  

For your particular usecase, what you want to use is [Zod](https://github.com/colinhacks/zod), you want runtime validation.  

tsafe might come in handy though, to make sure that the validation schema you've defined exactly matches the type you want to test against.  

Example of what your might want to do:   

```tsafe
import { assert, type Equals } from "tsafe/assert";
import { z } from "zod";

type MyType = { foo: string; bar: number; }[];

const zMyType = z.array(z.object({
    "foo": z.string(),
    "bar": z.number()
}));


// We make sure zArray is a schema that validates MyType.
assert<Equals<MyType, z.infer<typeof zMyType>>>();


// x is maybe assignable to MyType, maybe not.
declare const x: any;

try{

    zMyType.parse(x);

    console.log("x is assignable to MyType");

}catch{

    console.log("x wasn't assignable to MyType");

}
```   

Of course using `tsafe` is completely optional here, `tsafe` is only usefull for making sure that you have wrote the correct schema for the type you are trying to validate (it won't complile otherwise). But you could very well use your schema definition as your source of truth.  

Hope it helps.

**Comment by oxters168** [comment]
Thanks for the quick response. It turns out firebase was giving me an array, I just didn't realize I had a function that turned them into objects afterwards. I appreciate your recommendation and I'm sure Zod will be helpful to me.

**Comment by garronej** [comment]
You're welcome!
