### ISSUE TITLE
Assertion Equal bug for enums values

### ISSUE THREAD

**Issue by 3axap4eHko** [garronej/tsafe#33]
I consider types are equal if they are extend each other. Unfortunately it is not the case for Equal
```ts
enum Enum {
  A = "a",
  B = "b",
}

const values1 = Object.values(Enum);
const values2 = [Enum.A, Enum.B];

type AssertEqual<T, U> = T extends U ? (U extends T ? true : never) : never;

const result: AssertEqual<typeof values1, typeof values2> = true;

assert<Equal<typeof values1, typeof values2>>(true);
 ```

**Comment by garronej** [comment]
Hello @3axap4eHko,

While it’s inconvenient to have two types that you know are equal being deemed not equal by `assert<Equals<>>`, it is ultimately just an inconvenience. On the other hand, if `assert<Equals<>>` validated two types as identical when they actually aren’t, it would be a massive issue because you would be operating under a false assumption.

Let me give you an example of why I cannot replace the implementation of `Equals` with `Equals<T, U> = T extends U ? (U extends T ? true : never) : never;`:

![Example Image](https://github.com/user-attachments/assets/21998834-cdeb-49bf-bdae-01dbc7f99a40)

In practice, if your type isn’t a function or doesn’t contain a function, you can safely use `ExtendsEachOther` in place of `Equals`. I personally use this workaround sometimes for types that are too complex to be validated as equal by `Equals`.

I don't think there is a way to reduce the false negative of `Equal` unfortunately.   

I will add the `ExtendsEachOther<>` type to `tsafe` tomorrow. 👍🏻  

I hope it helps.

**Comment by 3axap4eHko** [comment]
Maybe it worth to name it as `LooseEqual` since you already have `StrictEqual` type assertion

**Comment by 3axap4eHko** [comment]
@garronej Also I've checked with function and it errors
```ts
type AssertEqual<T, U> = T extends U ? (U extends T ? true : never) : never;

type A = {  f: (x?: string) => void }
type B = {  f: (x: string) => void }

const resultFn: AssertEqual<A, B> = true; // Type 'boolean' is not assignable to type 'never'.
```
can you provide any false negative example to test

**Comment by garronej** [comment]
@3axap4eHko, sorry my answer was wrong the example I gave in my screenshot gave a false positive just because I didn't set the test case up properly.  

Here is an actual example that gives false positive:  

```ts
    type Equals<T, U> = T extends U ? (U extends T ? true : false) : false;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    type A = unknown[];
    type B = [unknown][];

    assert<Equals<A, B>>(); // Thoses type are deemed equals with the above implementation of Equals but not with the tsafe implementation.
```  

Ref: https://stackoverflow.com/questions/53807517/how-to-test-if-two-types-are-exactly-the-same/69378855#69378855

So I think it's save to use the ExtendsEachOther implem of the Equal function as long as the types compared are guarenteed to have no `any` in them...

**Comment by 3axap4eHko** [comment]
@garronej they are equal too [TypeScript playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAggznCAnYBRAjgVwIYBsA8AKgDRQCqAfFALxSFQQAewEAdgCZzlQD8UAFGQbM2nOryjAkmaAC4orCADdkASijzFKpAG4AUHtCRYNKNlYgA2gF19R6ACFTl1pgC2AI2TWb+vQGMAe1Y4YCgkCDhMXGAYJCRsEDh5eEQUDBwCGFIHKlopGR0gA)
```ts
type AssertEqual<T, U> = T extends U ? (U extends T ? true : never) : never;

type A = any[];
type B = [number][];

const resultArrays: AssertEqual<A, B> = true;
```

**Comment by garronej** [comment]
@3axap4eHko Well they shouldn't, A and B are not the same type here.

**Comment by 3axap4eHko** [comment]
@garronej  But they are the same
```ts
type A = any[];
type B = [number][];
```
comparison of these types can be simplified to compare their subtypes
```ts
type A = any;
type B = [number];
const resultArrays: AssertEqual<A, B> = true;
```
types are the same if you can assign them to each other, means `any` can be assigned to `[number]` and `[number]` can be assigned to `any`. Also I noticed that comparing anything to `any` except `any` returns `false` and `true` at the same time, so it is not false positive 
```ts
assert<Equals<number, any>>(false); // errors
assert<Equals<number, any>>(true); // errors

assert<Equals<any, any>>(false); // succeed
assert<Equals<any, any>>(true); // succeed
```
Am I missing something?

**Comment by garronej** [comment]
From a type theory perspective, you are correct that any value of type `any[]` is assignable to a value of type `[number][]` and vice versa.  
However, from an ensemble perspective, `[number][]` represents only a tiny subset of `any[]`.  
In other words, while `any[]` encompasses all possible arrays, `[number][]` includes only arrays of number singletons.  

For the type `Equals` to be useful in practice, two types must be considered equal only if and only if the set of values that satisfy each of them is identical.

**Comment by 3axap4eHko** [comment]
@garronej your explanation does make sense, but this assertions does not confirm your explanation
```ts
assert<Equals<any, any>>(false); // succeed
assert<Equals<any, any>>(true); // succeed
```

**Comment by garronej** [comment]
It might seem confusting but this is actually working as expected.  
See, there are two ways to use the assert function.  
When used in conjuction with equals you should not pass any parameter.  

```ts
import { assert, type Equals } from "tsafe/assert";

assert<Equals<A, B>>(); // Here you get a type error if A and B are not the same type.  
```
Theses kind of asserts statements could be removed from the build they are solely type safeguards but do not do anything at runtime.  

On the other end you can use the assert function to make assertion on a given value an narrow down it's type.  
Example:  

```ts
import { assert } from "tsafe/assert";

type Shape = {
    kind: "circle" | "square";
    radius?: number;
    sideLength?: number;
};

export function getArea(shape: Shape): number {
    switch(shape.kind){
        case "circle":
            assert(shape.radius !== undefined, "radius is required for circle");
            return Math.PI * shape.radius ** 2;
        case "square": 
            assert(shape.sideLength !== undefined, "sideLength is required for square");
            return shape.sideLength ** 2;
    }
}
```

Here the `Shape` type is not very strict. It is assumed that if the type is "circle" then the radius must be defined and if type is square the sideLengh must be defined but it is not enforced by the type system.  

So if we do that:  

<img width="396" alt="image" src="https://github.com/user-attachments/assets/1a8cea64-fbef-445f-aa72-9ab0463b2cb0">

We get types error and rightfully so. Using `!` should be avoided at all cost since it leads to errors that are hard to trace.  
Here using the assert function enables us to say:  
Okay, here I know for a fact that since the kind is "circle" the sideLenght must be defined, if it isn't throw new Error("radius is required for circle") and TypeScript, after this line you can assume that sideLengh is defined.  

<img width="690" alt="image" src="https://github.com/user-attachments/assets/2fa22686-3565-4c96-8a61-57554af26390">

This is a very different usecase, here we actually do something at runtime.  

I think that what got you confused is this gif:  

https://github.com/garronej/tsafe/releases/download/v0.0.1/tsafe_switch.gif  

Here I pass false, while using Equals. This is very missleading I should edit this example. This only make sens when we are comparing against `never`, here the `false` says: "We are not supposed to ever reach this point at runtime but if we ever do throw an exception.". This is kind of stupid though because if our type system is lying that much we have bigger probelms (we forgot to validate the shape of the data entering our system with something like zod).

**Comment by garronej** [comment]
I've updated the documentation so there's no ambiguity on what Equals does and how it's supposed to be used

https://docs.tsafe.dev/equals
