### ISSUE TITLE
Question: Runtime/Build time?

### ISSUE THREAD

**Issue by vernak2539** [garronej/tsafe#5]
Hello! Love this project. I do have one question. Do these checks only apply when it's runtime? Or, do they apply to build time? If I were to compile it down into just JS, would they still work?

**Comment by garronej** [comment]
Hi @vernak2539, I am sorry to disappoint you but if you are referring to `assert(is<T>(val))` there is no test actually performed. You are just saying "trust me typescript I know `val` is of type `T`.  If you where wrong you won't get build or runtime error when evaluating the `assert` statement.  

If there is a simple test that discriminate the type of your variable and that TypeScript can understand use it instead of `is` this way you will get runtime validation. 

![image](https://user-images.githubusercontent.com/6702424/143453407-a740878e-cf4b-4e3d-8cb1-e41abf566c11.png)

If there isn't such a test and you want to have an error at runtime in case you where wrong with your assertion you can use `typeGuard`.

![image](https://user-images.githubusercontent.com/6702424/143453884-56d2825e-3f21-4775-ad07-00056cf1d69e.png)

Be careful though, it is up to you to make sure that your check `obj.id.startsWith("foo-")` actually validate that obj is of type `Foo`.
