### ISSUE TITLE
assert incorrectly narrows type

### ISSUE THREAD

**Issue by husseinhere** [garronej/tsafe#6]
This code:
```
import { assert } from "tsafe";
const x: string | undefined = Math.random() < 0.5 ? undefined : "wtf";
assert(x);
let y: string = x;
console.log(y);
```
should not compile, but it does. Half the time it will console.log `undefined` and half the time will console.log `wtf`. Yet the type of `y` is supposedly a string.

It's not obvious why, so to avoid the spoiling the fun the explanation is base64 encoded:   `QXNzZXJ0IGlzIGRlZmluZWQgd2l0aCBgY29uZGl0aW9uOiBhbnkgPSB0cnVlYCB3aGljaCBjb21waWxlcyB0byAiaWYgY29uZGl0aW9uIGlzIHVuZGVmaW5lZCwgbWFrZSBpdCB0cnVlIiB3aGlsZSB0aGUgdHlwZSBzaWduYXR1cmUgZG9lc24ndCByZWZsZWN0IHRoaXMuIA==`

**Comment by garronej** [comment]
Hi @husseinhere,  
Thank you for the fun issue.  

I think there is a misunderstanding of what the `assert` function actually does. Maybe you think it is smarter than it is in reality.   

When you write `assert(x)` you say to typescript "Hey listen, trust be I know `x` will be truthy, if ever it isn't the case at runtime an exception will be thrown here so, please, assume for the rest of the execution that `x` is truthy".   

`x` is of type `string | undefined`  if it is truthy it must be a `string` because `undefined` is falsy.   
So, after the `assert(x)` instruction `x` is inferred as being of type `string` which is what is expected.  

` Math.random() < 0.5 ? undefined : "wtf";` is not relevent in this example, we are reasoning about types here.   
You could as well write your snipet like this:  

```typescript
import { assert } from "tsafe";
declare const x: string | undefined;
assert(x);
let y: string = x;
console.log(y);
```

or even: 

```typescript
import { assert } from "tsafe";
declare const x: string | undefined;
assert(x);
let y: string = x;
console.log(y);
```

or even: 

```typescript
import { assert } from "tsafe";
const x: string | undefined= null as any;
assert(x);
let y: string = x;
console.log(y);
```

As far as typescript is concerned, it makes no differences.

**Comment by husseinhere** [comment]
@garronej The example is actually quite relevant. 

What do you think the outcome of my example is? 

Presumedly you think it will do this:
> When you write assert(x) you say to typescript "Hey listen, trust be I know x will be truthy, if ever it isn't the case at runtime an exception will be thrown here so, please, assume for the rest of the execution that x is truthy".

But it doesn't.  Run it and see ;P

**Comment by husseinhere** [comment]
Basically the problem is default arguments don't work like you'd expect. Going to pure js, lets do this:

`function assert(cond = true) { console.log("You passed in: ", cond) }`

And using it:

`assert(1)` prints `You passed in:  1` // ok fine
`assert()` prints `You passed in:  true` // yup, default arg working as expected
`assert(false)` prints `You passed in: false` // obvious...
`assert(undefined)`  prints `You passed in:  true`  //oh fuck

**Comment by garronej** [comment]
You are right!  
My bad, thanks for reporting! I will fix.

**Comment by garronej** [comment]
Sorry, Is just that your initial message said "it shouldn't compile" I didn't look any further as it was expected to compile there is nonetheless a very serious bug that I am happy you caught.

**Comment by husseinhere** [comment]
I said it shouldn't compile, because the types don't match the runtime behavior. Basically the fix is either changing runtime behavior (which imo is preferred) or changing the type level behavior (i.e. `asserts condition || conditon === undefined` type thing)

**Comment by husseinhere** [comment]
BTW my fix you merged is probably going to cause problems:

now `assert<Equals<A,B>>()` is not going to compile.., which I guess is something you want :P

I guess you probably want to overload assert in typescript so it compiles (provide multiple definitions) and then use `arguments.length` to differentiate

**Comment by garronej** [comment]
Hi @husseinhere,  
I fixed the code after merging it. The condition deeded to be optional and that was it.
